/*
 * This is a generated file
 * 
 * Copyright 2021 QuickLogic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

`define BUILD_DATE 32'h20230710
`define BUILD_TIME 32'h00144748

//  PER_ID definitions
//  Hand-recomputed for N_UART=1, N_I2CM=0, N_FILTER=0 (originally 2, 2, 1) using the same
//  running-sum-of-N_x-in-perdef.json-order rule util/ioscript.py uses (verified against
//  the N_CAM 1->0 cut already committed in this file's history -- I2CM0 removed the same
//  way CAM0 was: instance-specific line deleted, everything downstream decremented by 1).
//  I2C master cut entirely: battery/wireless I2C now lives behind a separate coprocessor
//  reached over QSPI, so the main SoC no longer needs its own I2C master (per team
//  discussion, Sept 2026). NOT regenerated by the real tool -- see the note at PERIO_*
//  below.
`define PER_ID_UART      0
`define PER_ID_QSPIM     1
`define PER_ID_I2CM      3
`define PER_ID_I2SC      3
`define PER_ID_CSI2      3
`define PER_ID_HYPER     3
`define PER_ID_SDIO      3
`define PER_ID_CAM       4
`define PER_ID_JTAG      4
`define PER_ID_MRAM      4
`define PER_ID_FILTER    4
`define PER_ID_FPGA      4
`define PER_ID_EXT_PER   4

//  UDMA TX channels
`define CH_ID_TX_UART    0
`define CH_ID_TX_UART0   0
`define CH_ID_TX_QSPIM   1
`define CH_ID_TX_QSPIM0  1
`define CH_ID_TX_QSPIM1  2
`define CH_ID_CMD_QSPIM  3
`define CH_ID_CMD_QSPIM0 3
`define CH_ID_CMD_QSPIM1 4
`define CH_ID_TX_I2CM    5
`define CH_ID_TX_I2SC    5
`define CH_ID_TX_CSI2    5
`define CH_ID_TX_HYPER   5
`define CH_ID_TX_HYPER0  5
`define CH_ID_TX_JTAG    6
`define CH_ID_TX_MRAM    6
`define CH_ID_TX_FPGA    6
`define CH_ID_TX_EXT_PER 6

//  UDMA RX channels
`define CH_ID_RX_UART    0
`define CH_ID_RX_UART0   0
`define CH_ID_RX_QSPIM   1
`define CH_ID_RX_QSPIM0  1
`define CH_ID_RX_QSPIM1  2
`define CH_ID_RX_I2CM    3
`define CH_ID_RX_I2SC    3
`define CH_ID_RX_CSI2    3
`define CH_ID_RX_HYPER   3
`define CH_ID_RX_HYPER0  3
`define CH_ID_CAM        4
`define CH_ID_RX_JTAG    4
`define CH_ID_RX_MRAM    4
`define CH_ID_RX_FPGA    4
`define CH_ID_RX_EXT_PER 4

//  Number of channels
`define N_TX_CHANNELS  6
`define N_RX_CHANNELS  4

//  Define indices for sysio in IO bus
`define IOINDEX_JTAG_TCK_I            0
`define IOINDEX_JTAG_TDI_I            1
`define IOINDEX_JTAG_TDO_O            2
`define IOINDEX_JTAG_TMS_I            3
`define IOINDEX_JTAG_TRST_I           4
`define IOINDEX_SYSCLK_P_I            5
`define IOINDEX_RSTN_I                6
`define IOINDEX_STM_I                 44
`define IOINDEX_BOOTSEL_I             45
//  Width of perio bus
//  NOT UPDATED: this PERIO_* block and N_PERIO below are unchanged from this file's
//  generic (N_GPIO=32) state and do NOT reflect the wafer-space GF180 pin assignment
//  (N_GPIO=16, PWM 8-of-16 bonded, per docs/reference/pinout.md in core-v-mcu-wafer-space).
//  Regenerating this block correctly requires util/ioscript.py run with --pin-table
//  pointed at the real gf180-pin-table.csv, which was not available when this file was
//  edited. Do not trust N_PERIO or any PERIO_* value below until that's been run.
`define N_PERIO  47

//  define index locations in perio bus
`define PERIO_UART_NPORTS 2
`define PERIO_UART0_TX   0
`define PERIO_UART0_RX   1
`define PERIO_UART1_TX   2
`define PERIO_UART1_RX   3
`define PERIO_QSPIM_NPORTS 9
`define PERIO_QSPIM0_CLK 4
`define PERIO_QSPIM0_CSN0 5
`define PERIO_QSPIM0_CSN1 6
`define PERIO_QSPIM0_CSN2 7
`define PERIO_QSPIM0_CSN3 8
`define PERIO_QSPIM0_DATA0 9
`define PERIO_QSPIM0_DATA1 10
`define PERIO_QSPIM0_DATA2 11
`define PERIO_QSPIM0_DATA3 12
`define PERIO_QSPIM1_CLK 13
`define PERIO_QSPIM1_CSN0 14
`define PERIO_QSPIM1_CSN1 15
`define PERIO_QSPIM1_CSN2 16
`define PERIO_QSPIM1_CSN3 17
`define PERIO_QSPIM1_DATA0 18
`define PERIO_QSPIM1_DATA1 19
`define PERIO_QSPIM1_DATA2 20
`define PERIO_QSPIM1_DATA3 21
`define PERIO_I2CM_NPORTS 2
`define PERIO_I2CM0_SCL  22
`define PERIO_I2CM0_SDA  23
`define PERIO_I2CM1_SCL  24
`define PERIO_I2CM1_SDA  25
`define PERIO_I2SC_NPORTS 4
`define PERIO_I2SC0_SCK  26
`define PERIO_I2SC0_WS   27
`define PERIO_I2SC0_SD0  28
`define PERIO_I2SC0_SD1  29
`define PERIO_CSI2_NPORTS 0
`define PERIO_HYPER_NPORTS 0
`define PERIO_SDIO_NPORTS 6
`define PERIO_SDIO0_CLK  30
`define PERIO_SDIO0_CMD  31
`define PERIO_SDIO0_DATA0 32
`define PERIO_SDIO0_DATA1 33
`define PERIO_SDIO0_DATA2 34
`define PERIO_SDIO0_DATA3 35
`define PERIO_CAM_NPORTS 11
`define PERIO_CAM0_CLK   36
`define PERIO_CAM0_VSYNC 37
`define PERIO_CAM0_HSYNC 38
`define PERIO_CAM0_DATA0 39
`define PERIO_CAM0_DATA1 40
`define PERIO_CAM0_DATA2 41
`define PERIO_CAM0_DATA3 42
`define PERIO_CAM0_DATA4 43
`define PERIO_CAM0_DATA5 44
`define PERIO_CAM0_DATA6 45
`define PERIO_CAM0_DATA7 46
`define PERIO_JTAG_NPORTS 0
`define PERIO_MRAM_NPORTS 0
`define PERIO_FILTER_NPORTS 0
`define PERIO_FPGA_NPORTS 0
`define PERIO_EXT_PER_NPORTS 0
